name: Release OpenAgent

on:
  release:
    types: [ created, edited ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.6
        uses: actions/setup-java@v1
        with:
          java-version: 1.6

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.2.5

      - name: Get the release version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Get release version
        id: get_release_version
        run: |
          V=`echo ${{ steps.get_version.outputs.VERSION }} | sed -e's/v//g' | sed -e's/V//g'`; \
          echo ::set-output name=VERSION::${V}

      - name: Build and Publish Maven Package
        run: |
          mvn versions:set -DnewVersion=${{ steps.get_release_version.outputs.VERSION }}
          mvn versions:update-child-modules
          mvn versions:commit
          mvn -B package -Dmaven.test.skip=true
          mvn -B -DuseGitHubPackages=true deploy
